cafe_core_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'cafe_core_app'
urlpatterns = [
    path('', views.menu, name='menu'),
    path('menu', views.menu, name='menu'),
    path('meals/<meal_category>', views.meal_category, name='meal_category'),
    path('meal/<int:meal_id>', views.meal, name='meal'),
    path('meal_statistics', views.meal_statistics, name='meal_statistics'),
    path('grafic/<int:meal_id>', views.GraphsViewBar, name='grafic'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cafe_projeject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cafe_core_app.urls')),
    path('api/', include('users.urls')),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, UserView, Logout

from rest_framework import routers
from .api import TodoViewSet


router = routers.DefaultRouter()
router.register('api/user', TodoViewSet, 'user')

urlpatterns = [
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('user', UserView.as_view()),
    path('logout', Logout.as_view()),
]

cafe_core_app/models.py
from django.db import models

class Meal(models.Model):
    name = models.CharField('Название блюда', max_length=100)
    description = models.TextField('Описание блюда')
    price = models.IntegerField('Стоимость блюда')
    size = models.IntegerField('Грамовка блюда')

    class MealType(models.TextChoices):
        HOT_MEALS = 'Горячие блюда'
        DRINK = 'Напитки'
        DESSERT = 'Десерт'
        NO_TYPE = 'NO_TYPE'

    meal_type = models.CharField(
        max_length=30,
        choices=MealType.choices,
        default=MealType.NO_TYPE
    )
class MealClick(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.DO_NOTHING)
    click_date = models.DateTimeField('Дата клика')

class Users(models.Model):
    name = models.CharField('Name', max_length=100)

class Gallery(models.Model):
    image = models.ImageField(upload_to='static/img')
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, related_name='images')

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

cafe_core_app/views.py
from django.shortcuts import render
from .models import Meal, MealClick, Users, Gallery
from django.utils import timezone
import os

from matplotlib import pylab
from pylab import *

import jwt
from users.models import User

def menu(request):
    meal_categories = list(filter(lambda el: 'NO_TYPE' not in el[0], Meal.MealType.choices))
    return render(request, 'menu.html', {'meal_categories': meal_categories})

def meal_category(request, meal_category):
    meals_by_category = Meal.objects.filter(meal_type=meal_category)
    return render(request, 'meals.html', {'meals': meals_by_category, 'meal_category': meal_category})

def meal(request, meal_id):
    meal = Meal.objects.get(id=meal_id)
    meal.mealclick_set.create(click_date=timezone.now())
    img = Gallery.objects.filter(meal=meal)

    token = request.COOKIES.get('jwt')
    if token is not None:
        payload = jwt.decode(token, 'secret', algorithm=['HS256'])
        user = User.objects.filter(id=payload['id']).first()
        Users.objects.create(name=user.username)

    else:
        user = 'anonim'
        Users.objects.create(name=user)

    return render(request, 'meal.html', {'meal': meal, 'img': img})

def meal_statistics(request):
    click = MealClick.objects.all()
    users = Users.objects.all()

    def funk(param, click=None, users=None):
        food = []
        if click is not None:
            for i in click:
                food.append(i.meal.name)
        if users is not None:
            for i in users:
                food.append(i.name)

        pes = {}
        pes_ = {}
        for name in food:
            pes[name] = pes.get(name, 0) + 1
        for i, x in sorted(sorted(pes.items()), key=lambda x: x[1], reverse=True):
            if not len(pes_) == param:
                pes_[i] = pes_.get(i, x)
        return pes_
    pes_ = funk(3, click=click)
    res_ = funk(10, users=users)


    context = {
        # 'value': click,
        # 'users': users,
        'res': res_,
        'meal': pes_,
    }
    return render(request, 'meal_statistics.html', context=context)

matplotlib.use('Agg')
def GraphsViewBar(request,meal_id):
    namb = 0
    x = []
    y = []
    meal = Meal.objects.get(id=meal_id)

    for i in meal.mealclick_set.all():
        namb += 1
        x.append(namb)
        y.append(i.click_date.strftime("%d-%m-%y"))
    fig = plt.figure()
    plt.plot(y, x)
    plt.ylabel(meal.name)
    plt.xlabel('Дата')
    os.remove("cafe_core_app/static/img/core.png")
    fig.savefig('cafe_core_app/static/img/core.png')
    addr = 'img/core.png'
    plt.close(fig)
    return render(request, 'grafic.html', {'addr': addr})

users/views.py
from rest_framework.views import APIView
from .serializers import UserSerializer
from rest_framework.response import Response
from .models import User
from rest_framework.exceptions import AuthenticationFailed
import jwt, datetime


class RegisterView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

class LoginView(APIView):
    def post(self, request):
        email = request.data['email']
        password = request.data['password']

        user = User.objects.filter(email=email).first()

        if user is None:
            raise AuthenticationFailed('Пользователь не найден')

        payload = {
            'id': user.id,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=300),
            'iat': datetime.datetime.utcnow()
        }
        token = jwt.encode(payload, 'secret', algorithm='HS256').decode('utf-8')

        response = Response()
        response.set_cookie(key='jwt', value=token, httponly=True)
        response.data = {
            'jwt': token
        }

        return response

class UserView(APIView):
    def get(self, request):
        token = request.COOKIES.get('jwt')

        if not token:
            raise AuthenticationFailed('Не прошедший проверку подленности')

        try:
            payload = jwt.decode(token, 'secret', algorithm=['HS256'])

        except jwt.ExpiredSignatureError:
            raise AuthenticationFailed('Не прошедший проверку подленности')
        user = User.objects.filter(id=payload['id']).first()
        serializer = UserSerializer(user)
        return Response(serializer.data)

class Logout(APIView):
    def post(self, request):
        response = Response()
        response.delete_cookie('jwt')
        response.data = {
            'massage': 'Успешно'
        }
        return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" href="data:;base64,=">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        {% block title %}{% endblock %}
    </head>
    <body>
    <div class="container">

    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <span class="fs-4">Cafe Alise</span>
          </a>

          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="me-3 py-2 text-dark text-decoration-none" href="/">Главная страница</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/meal_statistics">Статистика</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/api/register">register</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/api/login">login</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/api/user">user</a>
                <a class="me-3 py-2 text-dark text-decoration-none" href="/api/logout">logout</a>
          </nav>
        </div>
        </div>
        <div class="container">
        {% block body %} {% endblock %}
            </div>
            </body>
</html>

templates/grafic.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %} {{meal.name}} {% endblock %}

{% block body %}
   <div class="col-md-8">
       <img src="{% static addr %}" alt="" title="">
    </div>

{% endblock %}

templates/meal.html
{% extends 'base.html' %}

{% block tittle %} {{meal.name}} {% endblock %}
{% load static %}
{% block body %}
{% csrf_token %}
    {% if meal %}
<div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2><b>Блюдо: </b> {{meal.name}}</h2>
        <p><b>Описание: </b> {{meal.description}}</p>
        <p><b>Цена: </b> {{meal.price}} BYN</p>
        <p><b>Размер: </b> {{meal.size}} г.</p>
    {% for i in img  %}
         <img src=" /{{ i.image }} " width="300" height="300" alt="{{meal.name}}">
    {% endfor %}
    </div>
    {% else %}
        Блюдо пустое :(
    {% endif %}
{% endblock %}

templates/meals.html
{% extends 'base.html' %}

{% block tittle %} {{meal_category}} {% endblock %}

{% block body %}
    {% if meals %}
        {% for meal in meals %}
    <div class="h-100 p-5 text-white bg-dark rounded-3">
        <style type="text/css">
   A {
    text-decoration: none; /* Убирает подчеркивание для ссылок */
   }
  </style>
            <h2><a href="{% url 'cafe_core_app:meal' meal.id %}" class="link-light">{{meal.name}}</a></h2>
            <a href="{% url 'cafe_core_app:grafic' meal.id %}" class="btn btn-secondary">График популярности блюда</a>
        </div><br>
        {% endfor %}
    {% else %}
        Пусто. Нету блюд в этой категории
    {% endif %}
{% endblock %}

templates/menu.html
{% extends 'base.html' %}

{% block tittle %} Меню {% endblock %}

{% block body %}
    {% if meal_categories %}
        {% for category in meal_categories %}
<div class="h-100 p-5 text-white bg-dark rounded-3">
          <style type="text/css">
   A {
    text-decoration: none; /* Убирает подчеркивание для ссылок */
   }
  </style>
            <h2><a href="{% url 'cafe_core_app:meal_category' category.0 %}" class="link-light">{{category.0}}</a></h2>

        </div><br>
        {% endfor %}
    {% else %}
        Нету даже категорий блюд
    {% endif %}
{% endblock %}